GET http://localhost:3000/restaurants

###
GET http://localhost:3000/restaurants/2

###
GET http://localhost:3000/restaurants/4/menu

###
POST http://localhost:3000/restaurants
Content-Type: application/json

{
    "name": "El coro de Pablo",
    "address": "Calle de pablitu",
    "menu": {
        "pizza": 8.49,
        "ensalada": 123
    }
}

###
POST http://localhost:3000/restaurants
Content-Type: application/json

{
    "name": "ssa",
    "address": "Calle de pablitu",
    "menu": {
        "pizza": 8.49,
        "ensalada": 123
    }
}

###
// Update menu of one restaurants
PATCH http://localhost:3000/restaurants/2/menu
Content-Type: application/json

{
    "menu" : {
        "pizza2" : 3,
        "otra": 4
    }

}

###
// Get all restaurants open
GET http://localhost:3000/restaurants/open


### 
// Set 
PATCH http://localhost:3000/restaurants/open/2

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/2
